config/routes.rb
Rails.application.routes.draw do
  root "profiles#index"

  resources :profiles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @profiles = Profile.all
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)

    if @profile.save
      redirect_to @profile
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])

    if @profile.update(profile_params)
      redirect_to @profile
    else
      render :edit, status: :unprocessable_entity
    end
  end


  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def profile_params
      params.require(:profile).permit(:firstname, :lastname, :description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/profiles/edit.html.erb
<%= form_with model: @profile, :html => { :class => "p-5" } do |form| %>
  <h1>Modifier ce Profil</h1>
  <div class="row mb-2">
    <div class="col form-group" >
      <%= form.label :firstname %><br>
      <%= form.text_field :lastname, class: "form-control" %>
    </div>
      <div class="col form-group">
      <%= form.label :lastname %><br>
      <%= form.text_field :lastname, class: "form-control" %>
    </div>
  </div>
  
    <div class="form-group mb-2" >
      <%= form.label :description %><br>
      <%= form.text_area :description, class: "form-control" %>
    </div>
  
    <div class="form-group mb-2">
      <%= form.label :photo %><br>
      <%= form.file_field :photo, class: "form-control" %>
    </div>

    <div>
      <%= form.submit "Enregistrer les modifications", class: "btn btn-primary" %>
    </div>
  <% end %>
  

app/views/profiles/index.html.erb
<h1>Tous les profiles</h1>

<!--<ul>
  <% @profiles.each do |profile| %>
    <li>
     <a href="/profiles/<%= profile.id %>">
      <%= profile.lastname %> <%= profile.firstname %>
      </a>
    </li>
  <% end %>
</ul>-->
 <div class="row">
<% @profiles.each do |profile| %>
<div class="card" style="width: 18rem; margin: 10px; display: flex">
<img class="card-img-top" src="<%= profile.image %>" alt="Image profile" style="max-width: 18rem;max-height:20rem">
</div>
<div class="card-body">
    <h5 class="card-title"><%= profile.lastname %> <%= profile.firstname %></h5>
    <p class="card-text"><%= profile.description %></p>
    <a href="/profiles/<%= profile.id %>" class="btn btn-primary">Consulter</a>
  </div>
</div>
<% end %>
</div>
<a href="/profiles/new">
<button class="btn btn-primary mt-1">Nouveau profile</button>
</a>
<!--<%= link_to "Nouveau Profile", new_profile_path %>-->

app/views/profiles/new.html.erb
<h1>Nouveau profile</h1>

<%= form_with model: @profile do |form| %>
  <div>
    <%= form.label :firstname %><br>
    <%= form.text_field :firstname %>
  </div>

  <div>
    <%= form.label :lastname %><br>
    <%= form.text_field :lastname %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :image %><br>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit "Enregistrer le nouveau profil" %>
  </div>
<% end %>

app/views/profiles/show.html.erb
<div class="card" style="max-width: 30rem;">
  <img class="card-img-top" src="<%= @profile.image %>" alt="Image">
  <div class="card-body">
    <h5 class="card-title"><%= @profile.lastname %> <%= @profile.firstname %></h5>
    <p class="card-text">Description: <%= @profile.description %></p>
  </div>
  <div class="card-body">
    <%= link_to "Mettre à jour", edit_profile_path(@profile), class: "card-link" %>
    <%= link_to "Supprimer", @profile, data: {
                                         turbo_method: :delete,
                                         turbo_confirm: "Etes-vous sûr de vouloir supprimer ce profil ?",
                                       }, method: :delete, class: "card-link" %>
  <a href="/"style="margin-top: 20px;">Revenir aux profiles</a>
                                   
  </div>
</div>